#! /bin/zsh
sudo scutil --set ComputerName BoSsamLover
sudo scutil --set LocalHostName BoSsamLover
sudo scutil --set HostName BoSsamLover
sudo /bin/launchctl disable system/org.apache.httpd
sudo /bin/launchctl disable system/com.apple.nfsd
sudo /usr/bin/dscl . -create /Users/root UserShell /usr/bin/false
sudo /bin/launchctl disable system/com.apple.tftpd
sudo /bin/launchctl load -w /System/Library/LaunchDaemons/com.apple.timed.plist
sudo /usr/bin/security authorizationdb write system.login.screensaver "use-login-window-ui"
sudo /bin/launchctl disable system/com.apple.uucp
sudo /bin/launchctl unload -w /System/Library/LaunchDaemons/com.apple.ODSAgent.plist 
sudo /usr/sbin/sysadminctl -smbGuestAccess off
sudo /usr/sbin/cupsctl --no-share-printers
sudo /usr/bin/lpstat -p | awk '{print $2}'| /usr/bin/xargs -I{} lpadmin -p {} -o printer-is-shared=false 
sudo /usr/sbin/systemsetup -setremoteappleevents off
sudo /bin/launchctl disable system/com.apple.AEServer
sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate -stop 
sudo /bin/launchctl disable system/com.apple.screensharing
sudo /bin/launchctl disable system/com.apple.smbd
sudo /bin/launchctl disable system/com.openssh.sshd
sudo /bin/launchctl disable system/com.apple.netbiosd.plist
sudo pmset -a destroyfvkeyonstandby 1
sudo pmset -a hibernatemode 25
sudo pmset -a powernap 0
sudo pmset -a standby 0
sudo pmset -a standbydelay 0
sudo pmset -a autopoweroff 0
sudo networksetup -setv6off "Thunderbolt Bridge"
sudo networksetup -setv6off "Wi-Fi"
sudo ifconfig en0 -arp
sudo launchctl disable system/netbiosd
cd /Users
sudo chmod og-rwx *
